const EXPO_ANDROID_CLIENT_ID = process.env.EXPO_ANDROID_CLIENT_ID;
const EXPO_IOS_CLIENT_ID = process.env.EXPO_IOS_CLIENT_ID;
const JWT_SECRET_KEY = process.env.JWT_SECRET_KEY;
module.exports = {EXPO_ANDROID_CLIENT_ID, EXPO_IOS_CLIENT_ID, JWT_SECRET_KEY};